### PR TITLE
Refactor PayU_Account magento plugin

### PR DESCRIPTION
**Pull request by cieslix**
I refactored most of code, but not all. I just tried to make this Magento plugin workable. I tested all functionality on test credentials and it should be tested on production. I will be glad if PayU test my changes as well :)

### CODE REVIEW

**Comment by firian** [comment]
These changes looks promising, but it's hard to find out what exactly did you change since you changed the formatting of the whole thing. If you bring back the old formatting we will review the commit sooner.

**Comment by cieslix** [comment]
It turns out that PayU_Account_Model_Config::getArrayFromJsonResponse has a problem to get data from http://www.openpayu.com/en/goods/plugin/magento/160/181/json/ and exception was thrown, so I had to remove it. In this commit you can check this changes https://github.com/macopedia/plugin_magento_160/commit/a6bb309067e6bdf6238a1295bf70a6e9c7adc121

**Comment by cieslix** [comment]
@firian about restoring old formatting this can be problem, the previous code was without any format or had it multiple, but not correct for Magento. So first thing was to make looks like php code psr-0/1/2 and compatible with Zend Framework 1 standards. Phpdocs were not in all places correctly placed, there were missing new lines at the end of files.

**Comment by agnagna** [comment]
Hi, the plugin works fine, thank you for your contribution :)

**Pull request merged**
